// flow-typed signature: 9ba0729ea20199060765de0fbbfb6f1d
// flow-typed version: <<STUB>>/semver_v7.1.1/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

// Not a complete definition.
declare module 'semver' {
  declare export function lt(string, string): boolean;
}
