// flow-typed signature: 3a2dfbbf459219b0d447c20256706d50
// flow-typed version: <<STUB>>/toml_v^3.0.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'toml' {
  declare export function parse(Buffer | string): Pojo;
}
