// flow-typed signature: f5d3d63ed2575dfab132af56330b1eae
// flow-typed version: <<STUB>>/yargs_v15.1.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yargs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yargs' {
  declare module.exports: any;
}
